# Generated by Django 2.0.5 on 2018-05-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AsignarTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contenidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=256)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskLearning.Acudiente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='grupoxprofesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gxp', to='taskLearning.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('grupos', models.ManyToManyField(through='taskLearning.grupoxprofesor', to='taskLearning.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='profesorxmateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pxm', to='taskLearning.Materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pxm', to='taskLearning.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_init', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bibliografia', models.CharField(max_length=500)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskLearning.Contenidos')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(through='taskLearning.profesorxmateria', to='taskLearning.Materia'),
        ),
        migrations.AddField(
            model_name='grupoxprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gxp', to='taskLearning.Profesor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskLearning.Grupo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tareas',
            field=models.ManyToManyField(through='taskLearning.AsignarTarea', to='taskLearning.Tarea'),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskLearning.Materia'),
        ),
        migrations.AddField(
            model_name='asignartarea',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to='taskLearning.Estudiante'),
        ),
        migrations.AddField(
            model_name='asignartarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to='taskLearning.Tarea'),
        ),
    ]
