# Generated by Django 2.0.5 on 2018-05-26 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskLearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materiaxgrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mxg', to='taskLearning.Grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mxg', to='taskLearning.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='materias',
            field=models.ManyToManyField(through='taskLearning.materiaxgrupo', to='taskLearning.Materia'),
        ),
    ]
