# Generated by Django 2.0.5 on 2018-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskLearning', '0002_auto_20180525_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='image',
            field=models.FileField(default=1, upload_to='media/profileImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='file',
            field=models.FileField(default=1, upload_to='media/tareas'),
            preserve_default=False,
        ),
    ]
