# Generated by Django 2.0.5 on 2018-06-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskLearning', '0003_auto_20180526_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas',
            name='contenido',
        ),
        migrations.DeleteModel(
            name='Temas',
        ),
    ]
