# Generated by Django 2.0.5 on 2018-07-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskLearning', '0007_auto_20180623_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='isvisibleGame',
            field=models.BooleanField(default=True),
        ),
    ]
